x = audioread('2A.wav');
h = audioread('2C.wav');
Xx = (fft(x));
Hh = (fft(h));
Spect_magnitude_Xx = abs(Xx);
Spect_magnitude_Hh = abs(Hh);
figure(1);
subplot(2,1,1);
plot(Spect_magnitude_Xx);
subplot(2,1,2);
plot(Spect_magnitude_Hh);
%y = xcorr(Spect_magnitude_Xx,Spect_magnitude_Hh);
y = xcorr(Xx,Hh);
%y = corr(Spect_magnitude_Xx);
figure(2); %subplot(3,1,1);
%stem(Xx);ylabel('Amplitude');
%subplot(3,1,2);
%stem(Hh);ylabel('Amplitude');
%subplot(3,1,3);
stem(fliplr(y));ylabel('Amplitude');
disp('The resultant signal is'); fliplr(y);